import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/steps/step1.png',
    title: "Begin with signing up",
    rating: 5,
    ratingCount: 8,
    price: 25,
    about: 'Start your trading journey by signing up and loging into your trading account on our comprehensive technology-driven trading platform',
    link:'/images/avatars/number1.svg',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Choose your strategy',
    rating: 5,
    ratingCount: 15,
    price: 20,
   about: 'Protect yourself from the ups and downs of the market by including your preferred level of risk into the trading algorithm. Our systems will handle everything else for you.',
    link:'/images/avatars/number2.svg',
  },
  {
    id: 3,
    cover: '/images/courses/steps/step3.png',
    title: 'Include the risk factor',
    rating: 4,
    ratingCount: 7,
    price: 30,
   about: 'You can decide how to trade on our platform. Pick expert trading plans made by professionals, make your own special plan, and choose from a bunch of different products according to you requirements.',
    link:'/images/avatars/number3.svg',
  },
  {
    id: 4,
    cover: '/images/courses/steps/step2.jpg',
    title: 'Trade at your fingertips',
    rating: 4,
    ratingCount: 12,
    price: 30,
   about: "Once you've adjusted everything the way you prefer, you can start your trading journey using our platform. You'll experience the advantages of a smart and automated trading system, no matter where you are in the world.",
    link:'/images/avatars/number4.svg',
  },
  // {
  //   id: 5,
  //   cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
  //   title: 'Modern React with MUI & Redux',
  //   rating: 4,
  //   ratingCount: 32,
  //   price: 35,
  //  about: 'Intermediate',
  //   link:'/images/avatars/number1.svg',
  // },
  // {
  //   id: 6,
  //   cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
  //   title: 'Ethical Hacking Bootcamp Zero to Mastery',
  //   rating: 5,
  //   ratingCount: 14,
  //   price: 35,
  //  about: 'Beginner',
  //   link:'/images/avatars/number1.svg',
  // },
  // {
  //   id: 7,
  //   cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
  //   title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
  //   rating: 4,
  //   ratingCount: 6,
  //   price: 25,
  //  about: 'Beginner',
  //   link:'',
  // },
]
